version: '3'
services:
  redis-master:
    image: redis
    container_name: redis-master
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
  redis-slave-1:
    image: redis
    container_name: redis-slave-1
    ports:
      - "6380:6379"
    command: redis-server --slaveof redis-master 6379
  redis-slave-2:
    image: redis
    container_name: redis-slave-2
    ports:
      - "6381:6379"
    command: redis-server --slaveof redis-master 6379